using System.Collections;
using System.Collections.Generic;
using UnityEngine;

[CreateAssetMenu]
public class StarValues : ScriptableObject
{   
    public float scale;

    public Color color;
    public Color cellColor;

    public float cellDensity;
    public float solarFlare;
    public float cellSpeed;

    public List<string> starNames = new()
        {
            "Galaxia",
            "Nebulastra",
            "Stellara",
            "Cosmosis",
            "Aurorium",
            "Celestia",
            "Novaflare",
            "Luminara",
            "Astrophia",
            "Twilightium",
            "Orbitron",
            "Sunsprite",
            "Ecliptica",
            "Supernovus",
            "Glimmerstar",
            "Interstella",
            "Astralite",
            "Glowburst",
            "Stargaze",
            "Cosmicluster",
            "Starbound",
            "Nebulight",
            "Eclipsea",
            "Spectron",
            "Galactix",
            "Infinitya",
            "Lunaria",
            "Constella",
            "Radianta",
            "Spacebeam",
            "Astroblaze",
            "Orbitalis",
            "Solaris",
            "Skyward",
            "Stellaris",
            "Galactron",
            "Aurorastra",
            "Nebuluna",
            "Luminex",
            "Celestrix",
            "Supernova",
            "Twilightron",
            "Stellarnova",
            "Orbitalis",
            "Sunburst",
            "Astroflare",
            "Cosmicnova",
            "Starflare",
            "Nebulaflare",
            "Eclipticus",
            "Spectra",
            "Galactra",
            "Lunatrix",
            "Constellaris",
            "Radiatrix",
            "Spacestar",
            "Astroburst",
            "Orbita",
            "Solarium",
            "Skyblaze",
            "Stellara",
            "Galaxtra",
            "Astraluna",
            "Nebulon",
            "Lumina",
            "Celestus",
            "Stellaria",
            "Nebulastra",
            "Lunatron",
            "Orbitron",
            "Solarix",
            "Skytrix",
            "Galaxar",
            "Astralux",
            "Nebulor",
            "Luminor",
            "Celestor",
            "Aurorix",
            "Stellara",
            "Nebulite",
            "Lumine",
            "Celestria",
            "Galaxus",
            "Aurorion",
            "Stellarium",
            "Nebuloid",
            "Luminoid",
            "Celestion",
            "Galaxian",
            "Aurorius",
            "Stellarius",
            "Nebulus",
            "Luminus",
            "Celestus",
            "Galaxar",
            "Aurora",
            "Stella",
            "Nebula",
            "Luminara",
            "Celestium"
        };
}
